# Header



menu:
  Home: /    
  所有文章: /archives
  一蓑烟雨任平生: /tags/youth  


# SubNav
subnav:
  github: "https://github.com/khan-yin"
  #weibo: "#"
  # rss: "/atom.xml"
  zhihu: "https://www.zhihu.com/people/khan-55-55"
  # qq: "/assets/qq.jpg"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  bilibili: "https://space.bilibili.com/351001593"
  #acfun: "#"
  #facebook: "#"
  #google: "#"
  twitter: "https://x.com/jack_kehan"
  mail: "mailto:khany@foxmail.com"
  #linkedin: "#"

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
# excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式math
math:
  engine: 'mathjax' # or 'katex'
  # mathjax:
  #   src: # "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
  #   config:
  #     # MathJax config
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /assets/zfb.jpg
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 0
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /assets/liangx.jpg

#你的头像url
avatar: /assets/liang.jpg

#是否开启分享
share_jia: false

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#0e84f9'
  # 右滑板块背景
  slider: 'linear-gradient(0deg,#f45050,#0e84f9)' #'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '标签检索'
  friends: '友情链接'
  archives: '归档'
  aboutme: '关于'

friends:
  我的掘金: https://juejin.cn/user/2365804755816072
  广平的小世界: https://xgpax.top/
  rbgg: https://www.hanpy.plus/
  川哥:  https://zichuan-liu.github.io/
  kingfish404: https://kingfish404.cn/
  伟哥:  http://hanweiblog.top/
  祺哥: https://rq-wu.github.io/
  俊哥: http://duing.site/
  梁sir: http://moyisuiying.com/

archives:
  七百年后: /archives/2100/
  2025年 φ(≧ω≦*)♪: /archives/2025/
  2024年 ヾ(=･ω･=)o: /archives/2024/
  2023年 (๑•̀ㅂ•́)و✧: /archives/2023/
  2022年 ￣ω￣=: /archives/2022/
  2021年 (ಥ_ಥ): /archives/2021/
  2020年 ╮(╯_╰)╭: /archives/2020/
  
  # 2019年 φ(≧ω≦*)♪: /archives/2019/
  # 

aboutme: 在日落大道的你与我握手 <br /> 发觉太想和你闯遍这地球


# 网易云音乐插件
music:
  enable: true
  #id: 1332647902  # 网易云分享的ID
  autoplay: false  # 是否开启自动播放

# timeline:
#   num: 1
#   word: 2018/08/16-Start 
#   num: 2
#   word: writing
#   num: 3
#   word: More
live2d:
  enable: false
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-none
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true